// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/10/2024, 20:15:13
const configMerger = require("C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/plugins/**/*.{js,ts,mjs}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/composables/**/*.{js,ts,mjs}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/utils/**/*.{js,ts,mjs}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "C:/Users/serge/OneDrive/Documents/GitHub/minderik_1/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
